from fastapi import APIRouter, Depends, HTTPException
from src.budgets.models import (
    BudgetGroupCreate,
    BudgetGroupUpdate,
    BudgetGroupResponse,
    BudgetGroupOrm,
    BudgetItemCreate,
	BudgetItemUpdate,
    BudgetItemResponse,
    BudgetItemOrm
)
from src.budgets.utils import validate_group_id_in_db
from src.database import get_db
from sqlalchemy import select
from sqlalchemy.orm import selectinload
from sqlalchemy.ext.asyncio import AsyncSession
from collections.abc import Sequence

router = APIRouter()


# use POST because this is not idempotent. Will create a new item every valid request
@router.post("/groups/new", response_model=BudgetGroupResponse)
async def create_new_budget_group(
    new_budget_group: BudgetGroupCreate,
    db: AsyncSession=Depends(get_db)
) -> BudgetGroupOrm:
    new_group_orm = BudgetGroupOrm(**new_budget_group.model_dump())
    db.add(new_group_orm)
    await db.commit()

    # gets back the complete object as generated by Postgres including
    # the id attribute, and forces the load of the (empty) array of budget items
    await db.refresh(new_group_orm, attribute_names=["budget_items"])
    
    return new_group_orm


# The query here includes an option for selectinload. By default, BudgetGroupOrm
# does not load all data from db inside this function, but does a lazy load instead.
# Leaving this option out would result in many queries being run at serialization time.
# selectinload causes only one additional query to run so that everything is filled out.
# Anyway, the async engine would have resulted in runtime errors when those serialization
# queries run, so this option solves two problems: query efficiency, and avoid runtime
# error for async.
@router.get("/groups/getall", response_model=list[BudgetGroupResponse])
async def get_all_groups_for_user_budget(db: AsyncSession=Depends(get_db)) -> Sequence[BudgetGroupOrm]:
    query = select(BudgetGroupOrm).options(selectinload(BudgetGroupOrm.budget_items))
    result = await db.execute(query)
    return result.scalars().all()


@router.post(
    "/groups/{budget_group_id}/update",
    response_model=BudgetGroupResponse
)
async def update_budget_group(
    budget_group_id: int,
    new_fields: BudgetGroupUpdate,
    db: AsyncSession=Depends(get_db)
) -> BudgetGroupOrm:
    group_updated_orm = await db.get(
        entity=BudgetGroupOrm, ident=budget_group_id,
        options=[selectinload(BudgetGroupOrm.budget_items)]
    )
    if group_updated_orm is None:
        raise HTTPException(status_code=404, detail="Budget group not found")
    
    group_updated_orm.name = new_fields.name
    
    # this is the least complicated, easiest to maintain way.
    # if it becomes a performance issue, diff the changes
    # only change the necessary items. most of the time it
    # is probably zero or 1 item that changes for each group update
    # (add item to group, take it away, change group name)
    # except when groups have just been created of many items.
    group_updated_orm.budget_items = []
    
    new_item_ids = new_fields.budget_item_ids
    for item_id in new_item_ids:
        item_orm = await db.get(entity=BudgetItemOrm, ident=item_id)
        
        if item_orm is None:
            raise HTTPException(status_code=422, detail="Bad request: budget item doesnt exist.")
        
        group_updated_orm.budget_items.append(item_orm)

    await db.commit()
    await db.refresh(group_updated_orm, attribute_names=["budget_items"])
    return group_updated_orm


@router.delete("/groups/{budget_group_id}/delete", status_code=204)
async def delete_budget_group(
    budget_group_id: int,
    db: AsyncSession=Depends(get_db)
) -> None:
    group_to_delete = await db.get(entity=BudgetGroupOrm, ident=budget_group_id)
    if group_to_delete is None:
        raise HTTPException(status_code=404, detail="Budget group not found")
    await db.delete(group_to_delete)
    await db.commit()

# use POST because this is not idempotent. Will create a new item every valid request
@router.post("/items/newitem", response_model=BudgetItemResponse)
async def create_new_budget_item(
    new_budget_item: BudgetItemCreate,
    db: AsyncSession=Depends(get_db)
) -> BudgetItemOrm:
    async def populate_item_id(orm: BudgetItemOrm) -> None:
        # start tracking the new item orm and have Postgres assign an id to it.
        # the transaction has been entered, but the db is not written yet.
        db.add(new_item_orm)
        await db.flush()

    async def validate_group_id_in_db(group_id: int | None) -> BudgetGroupOrm | None:
        # specifying no group is a valid request.
        if group_id is None:
             return None
        
        group = await db.get(entity=BudgetGroupOrm, ident=group_id)
        if group is None:
             raise HTTPException(status_code=422, detail="Bad request: specified a nonexistent budget group")
        
        return group

    group_id = new_budget_item.budget_group_id
    await validate_group_id_in_db(group_id)

    new_item_orm = BudgetItemOrm(
        name = new_budget_item.name,
        assigned = new_budget_item.assigned,
        spent = new_budget_item.spent,
        budget_group_id = new_budget_item.budget_group_id
    )

    await populate_item_id(new_item_orm)
    await db.commit()
    return new_item_orm


@router.get("/items/{budget_item_id}", response_model=BudgetItemResponse)
async def get_budget_item(budget_item_id: int, db: AsyncSession=Depends(get_db)) -> BudgetItemOrm:
    budget_item = await db.get(entity=BudgetItemOrm, ident=budget_item_id)
    if budget_item is None:
        raise HTTPException(status_code=404, detail="Budget item not found")
    return budget_item


@router.post("/items/{budget_item_id}/update", response_model=BudgetItemResponse)
async def update_budget_item(
    budget_item_id: int,
    updated_budget_item: BudgetItemUpdate,
    db: AsyncSession=Depends(get_db)
) -> BudgetItemOrm:
    item_orm = await db.get(entity=BudgetItemOrm, ident=budget_item_id)
    if item_orm is None:
        raise HTTPException(status_code=404, detail="Budget item not found")
    
    group_id = updated_budget_item.budget_group_id
    await validate_group_id_in_db(group_id, db)
    
    # get update only the fields given in the request
    updated_fields = updated_budget_item.model_dump(exclude_unset=True).items()

    for field, value in updated_fields:
        setattr(item_orm, field, value)

    await db.commit()
    return item_orm


# deletes the item at the id, or returns 404 if not found.
@router.delete("/items/{budget_item_id}/delete", status_code=204)
async def delete_budget_item(
    budget_item_id: int,
    db: AsyncSession=Depends(get_db)
) -> None:
    item_to_delete = await db.get(entity=BudgetItemOrm, ident=budget_item_id)
    if item_to_delete is None:
        raise HTTPException(status_code=404, detail="Budget item not found")
    
    await db.delete(item_to_delete)
    await db.commit()