from .models import TransactionSchema, TransactionType

transactions: list[TransactionSchema] = [
    TransactionSchema(
        id="1",
        date="2026-02-02",
        merchant="Salary Deposit",
        category="Income",
        amount=5000,
        type=TransactionType.income,
        accountId="1",
    ),
    TransactionSchema(
        id="2",
        date="2026-02-01",
        merchant="Whole Foods Market",
        category="Groceries",
        amount=-125.43,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="3",
        date="2026-02-01",
        merchant="Shell Gas Station",
        category="Transportation",
        amount=-52.0,
        type=TransactionType.expense,
        accountId="3",
    ),
    TransactionSchema(
        id="4",
        date="2026-01-31",
        merchant="Netflix Subscription",
        category="Entertainment",
        amount=-15.99,
        type=TransactionType.expense,
        accountId="3",
    ),
    TransactionSchema(
        id="5",
        date="2026-01-31",
        merchant="Starbucks",
        category="Food & Dining",
        amount=-8.75,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="6",
        date="2026-01-30",
        merchant="Electric Company",
        category="Utilities",
        amount=-145.0,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="7",
        date="2026-01-29",
        merchant="Target",
        category="Shopping",
        amount=-87.34,
        type=TransactionType.expense,
        accountId="3",
    ),
    TransactionSchema(
        id="8",
        date="2026-01-28",
        merchant="Olive Garden",
        category="Food & Dining",
        amount=-65.5,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="9",
        date="2026-01-27",
        merchant="Gym Membership",
        category="Health",
        amount=-50.0,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="10",
        date="2026-01-26",
        merchant="Amazon",
        category="Shopping",
        amount=-234.99,
        type=TransactionType.expense,
        accountId="3",
    ),
    TransactionSchema(
        id="11",
        date="2026-01-25",
        merchant="Freelance Project",
        category="Income",
        amount=1250,
        type=TransactionType.income,
        accountId="1",
    ),
    TransactionSchema(
        id="12",
        date="2026-01-24",
        merchant="Delta Airlines",
        category="Travel",
        amount=-450.0,
        type=TransactionType.expense,
        accountId="3",
    ),
    TransactionSchema(
        id="13",
        date="2026-01-24",
        merchant="Uber",
        category="Transportation",
        amount=-28.5,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="14",
        date="2026-01-23",
        merchant="Trader Joe's",
        category="Groceries",
        amount=-89.23,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="15",
        date="2026-01-23",
        merchant="Chipotle",
        category="Food & Dining",
        amount=-12.45,
        type=TransactionType.expense,
        accountId="3",
    ),
    TransactionSchema(
        id="16",
        date="2026-01-22",
        merchant="Best Buy",
        category="Shopping",
        amount=-399.99,
        type=TransactionType.expense,
        accountId="3",
    ),
    TransactionSchema(
        id="17",
        date="2026-01-22",
        merchant="Spotify Subscription",
        category="Entertainment",
        amount=-10.99,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="18",
        date="2026-01-21",
        merchant="Water Company",
        category="Utilities",
        amount=-65.0,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="19",
        date="2026-01-20",
        merchant="CVS Pharmacy",
        category="Health",
        amount=-45.67,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="20",
        date="2026-01-20",
        merchant="Panera Bread",
        category="Food & Dining",
        amount=-18.9,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="21",
        date="2026-01-19",
        merchant="Shell Gas Station",
        category="Transportation",
        amount=-48.0,
        type=TransactionType.expense,
        accountId="3",
    ),
    TransactionSchema(
        id="22",
        date="2026-01-18",
        merchant="Costco",
        category="Groceries",
        amount=-156.78,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="23",
        date="2026-01-18",
        merchant="Client Payment",
        category="Income",
        amount=800,
        type=TransactionType.income,
        accountId="1",
    ),
    TransactionSchema(
        id="24",
        date="2026-01-17",
        merchant="Home Depot",
        category="Shopping",
        amount=-178.45,
        type=TransactionType.expense,
        accountId="3",
    ),
    TransactionSchema(
        id="25",
        date="2026-01-17",
        merchant="Movie Theater",
        category="Entertainment",
        amount=-35.0,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="26",
        date="2026-01-16",
        merchant="Starbucks",
        category="Food & Dining",
        amount=-6.85,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="27",
        date="2026-01-15",
        merchant="Internet Service",
        category="Utilities",
        amount=-89.99,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="28",
        date="2026-01-15",
        merchant="Uber Eats",
        category="Food & Dining",
        amount=-32.5,
        type=TransactionType.expense,
        accountId="3",
    ),
    TransactionSchema(
        id="29",
        date="2026-01-14",
        merchant="Walgreens",
        category="Health",
        amount=-23.45,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="30",
        date="2026-01-13",
        merchant="Whole Foods Market",
        category="Groceries",
        amount=-98.67,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="31",
        date="2026-01-12",
        merchant="Lyft",
        category="Transportation",
        amount=-19.75,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="32",
        date="2026-01-12",
        merchant="Apple Store",
        category="Shopping",
        amount=-129.0,
        type=TransactionType.expense,
        accountId="3",
    ),
    TransactionSchema(
        id="33",
        date="2026-01-11",
        merchant="Dunkin' Donuts",
        category="Food & Dining",
        amount=-9.25,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="34",
        date="2026-01-10",
        merchant="Gas Company",
        category="Utilities",
        amount=-112.0,
        type=TransactionType.expense,
        accountId="1",
    ),
    TransactionSchema(
        id="35",
        date="2026-01-09",
        merchant="Parking Fee",
        category="Transportation",
        amount=-15.0,
        type=TransactionType.expense,
        accountId="1",
    ),
]