extend-exclude = ["migrations/"]

[lint]
# Added E501: ruff format does not fix long lines that are comments, string
# literals, etc, this rule flags the lines
extend-select = ["FAST", "ANN2", "E501"]