"""add budget item id to transactions, leave category for now.

Revision ID: 4a3b02a1ff27
Revises: 88e361718f8c
Create Date: 2026-03-15 16:27:33.209867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3b02a1ff27'
down_revision: Union[str, Sequence[str], None] = '88e361718f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('budget_item_id', sa.Integer(), nullable=True))
    op.alter_column('transactions', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               postgresql_using='date::date',
               existing_nullable=False)
    op.create_foreign_key(None, 'transactions', 'budget_items', ['budget_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('transactions', 'budget_item_id')
    # ### end Alembic commands ###
