"""

Revision ID: 919e2fa9d548
Revises: dbdec0ffafac
Create Date: 2026-03-02 17:45:19.464491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919e2fa9d548'
down_revision: Union[str, Sequence[str], None] = 'dbdec0ffafac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_id-year-month'), 'envelopes', type_='unique')
    op.create_unique_constraint('unique_budget_item-year-month', 'envelopes', ['budget_item_id', 'year', 'month'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_budget_item-year-month', 'envelopes', type_='unique')
    op.create_unique_constraint(op.f('unique_id-year-month'), 'envelopes', ['id', 'year', 'month'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
