"""update budget_items foreign key rule for delete

Revision ID: cef766b4b200
Revises: 83a6679daa53
Create Date: 2026-02-26 19:26:45.067997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef766b4b200'
down_revision: Union[str, Sequence[str], None] = '83a6679daa53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('budget_items_budget_group_id_fkey'), 'budget_items', type_='foreignkey')
    op.create_foreign_key(None, 'budget_items', 'budget_groups', ['budget_group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budget_items', type_='foreignkey')
    op.create_foreign_key(op.f('budget_items_budget_group_id_fkey'), 'budget_items', 'budget_groups', ['budget_group_id'], ['id'])
    # ### end Alembic commands ###
