"""

Revision ID: dbdec0ffafac
Revises: 11818996ad35
Create Date: 2026-03-02 15:59:16.711677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdec0ffafac'
down_revision: Union[str, Sequence[str], None] = '11818996ad35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envelopes',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('assigned', sa.Float(), nullable=False),
    sa.Column('budget_item_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('assigned >= 0', name='assigned_zero_or_greater'),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='month_in_range'),
    sa.CheckConstraint('year > 0', name='year_greater_than_zero'),
    sa.ForeignKeyConstraint(['budget_item_id'], ['budget_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'year', 'month', name='unique_id-year-month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('envelopes')
    # ### end Alembic commands ###
