"""

Revision ID: ecf49ee7a9eb
Revises: 
Create Date: 2026-03-01 20:41:32.204895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf49ee7a9eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_groups',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('assigned', sa.Float(), nullable=False),
    sa.Column('spent', sa.Float(), nullable=False),
    sa.Column('budget_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['budget_group_id'], ['budget_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('income', 'expense', name='transactiontype'), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('budget_items')
    op.drop_table('budgets')
    op.drop_table('budget_groups')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
